language: r
warnings_are_errors: false
sudo: required

r_packages:
  - covr

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev libudunits2-dev
  - sudo apt-get install -y libfreetype6-dev libpoppler-cpp-dev libssl-dev

before_script:
  - Rscript -e 'install.packages(c("devtools", "mapview"))'
  - Rscript -e 'install_github(c("KevCaz/recruitR", "inSileco/letiRmisc", "inSileco/graphicsUtils"))'


after_success:
  - Rscript -e 'covr::codecov()'
