---
title: Seedlings recruitment analysis of Solarik et al. XXXX paper.
author: Kevin Cazelles and Kevin Solarik
date: '`r Sys.Date()`'
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
---

<br>
<br>

This vignette aims at guiding the reader through the different steps of the analysis we carried out in Solarik _et al._ XXXX. Data, R code and this vignette are available at <https://github.com/KevCaz/seedlingsRecruitmentAnalysis>.

# Data

<br>

## Sites of the study

Recruitment data have been measured on three different sites:

- 'abi': Abitibi
- 'bic': Le Bic
- 'sut': Sutton

The map below show the location of those sites. For each sites some extra information are available on clicks.

```{r map, message=FALSE, echo=FALSE, fig.width=9}
datS <- data.frame(
  id = c('abi', 'bic', 'sut'),
  name = c('Abitibi-Temiscaminque', 'Le Bic', 'Sutton'),
  lon = c(-79.401219, -68.817719, -72.541297),
  lat = c(48.162539, 48.333619, 45.112803),
  plots= c(400, 1024, 2000)
)
##
rownames(datS) <- datS$id
spSite <- sp::SpatialPointsDataFrame(
  datS[,c('lon', 'lat')],
  data = datS,
  proj4string = sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")
 )
 mapview::mapview(spSite)@map

```


<br>

## Tree species of the study

| abbr1 | abbr2 | Scientific Names      | TSN    |abi  |bic  |sut  |
|:------|:------|:----------------------|:-------|:----|:----|:----|
| BF    | ABBA  | Abies balsamea        | 18032  |TRUE |TRUE |TRUE |
| RM    | ACRU  | Acer rubrum           | 28728  |TRUE |TRUE |TRUE |
| SM    | ACSA  | Acer saccharum        | 28731  |TRUE |TRUE |TRUE |
| YB    | BEAL  | Betula alleghaniensis | 19481  |TRUE |TRUE |TRUE |
| WB    | BEPA  | Betula papyrifera     | 19489  |TRUE |TRUE |TRUE |
| AB    | FAGR  | Fagus grandifolia     | 19462  |TRUE |TRUE |TRUE |
| AS    | POTR  | Populus tremuloides   | 195773 |TRUE |TRUE |TRUE |

: Abbreviations, names, TSN (Taxonomic Serial Number, viti the [Integrated
  Taxonomic Information System website](https://www.itis.gov/pdf/faq_itis_tsn.pdf)
  for more details about TSN) of the tree species considered and their
  respective presence in the three sites of the study.


<br>

## Recruitment data

A link to the dataset would hopefully be available before publication.








# Statistical models

Below are detailed all the steps we used during the study.

## Model

## Parameters

| Ecological process  |abbr  |number of parameters|
|:--------------------|:-----|:-------------------|
| dispersion          |disp  |2                   |
| neighborhood effect |neigh |5                   |
| favorability        |favo  |1                   |


### Kernels

| numb | disp | which          | clip  |
|:-----|:-----|:---------------|:------|
|0     |--    |non-significant | -     |
|1     |dc    |lognormal       |clip   |
|2     |d-    |lognormal       |no-clip|
|3     |Dc    |power-exponetial|clip   |
|4     |D-    |power-exponetial|no-clip|


### Overall strategy of our analysis

Likelihood optimization using simulated annealing
(implemented by the [GenSA](https://cran.r-project.org/web/packages/GenSA/index.html) package).
For different models (40 models for each combination site x species x year x age).




<br><br>
# Numerical implementation
